name: [ProjectName]
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - notebook=6.1.5
  - ipython=7.19.0
  - ipykernel=5.4.2
  - numpy=1.19.4
  - scipy=1.5.3
  - scikit-learn=0.23.3
  - matplotlib=3.3.3
  - pandas=1.1.5
  - tqdm=4.54.1
  - pendulum=2.1.2
